version: '3' # Version of the Docker Compose file format
services:
  radio-player:
    restart: always
    container_name: radio-player
    build:
      context: .
    hostname: player.local
    volumes:
      - ./public/assets:/home/node/joujmafm/dist/assets
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8080:8080"
    networks:
      - frontend
networks:
  frontend: # Name of our shared network that containers will use
